[build]
  publish = "build"
  command = "npm run build"

  [[redirects]]
  from = "/saved-news"
  to = "/"
  status = 200
  force = true

  [[redirects]]
  from = "/signin"
  to = "https://newsexplorer-api.herokuapp.com/signin"
  status = 200
  force = true

    [[redirects]]
  from = "/signup"
  to = "https://newsexplorer-api.herokuapp.com/signup"
  status = 200
  force = true